# Generated by Django 3.0.8 on 2020-07-21 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0006_auto_20200721_0455'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.CharField(max_length=4),
        ),
    ]
