# Generated by Django 3.0.8 on 2020-07-22 06:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0008_auto_20200722_0551'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coursesubject',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_subject', to='course.Course'),
        ),
        migrations.AlterField(
            model_name='coursesubject',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_subject', to='course.Subject'),
        ),
    ]
