# Generated by Django 3.0.8 on 2020-07-28 02:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0010_semestergrade'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreRequisiteSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite_set', to='course.Subject')),
            ],
        ),
        migrations.CreateModel(
            name='PreRequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prerequisite_set', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite', to='course.PreRequisiteSet')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prerequisite', to='course.Subject')),
            ],
        ),
    ]
