# Generated by Django 3.0.8 on 2020-07-29 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0011_prerequisite_prerequisiteset'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='already_set_prerequisite',
            field=models.BooleanField(default=False),
        ),
    ]
