# Generated by Django 3.0.8 on 2020-08-03 01:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0014_equivalence_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='equivalence',
            old_name='abrangencia',
            new_name='coverage',
        ),
        migrations.RenameField(
            model_name='equivalence',
            old_name='direcao',
            new_name='direction',
        ),
        migrations.RemoveField(
            model_name='equivalence',
            name='destino',
        ),
        migrations.RemoveField(
            model_name='equivalence',
            name='disciplina',
        ),
        migrations.AddField(
            model_name='equivalence',
            name='destination',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='destination_eq', to='course.Subject'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='equivalence',
            name='subject',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='subject_eq', to='course.Subject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='option',
            name='equivalence',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='course.Equivalence'),
        ),
    ]
