# Generated by Django 3.0.8 on 2020-08-06 04:49

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0015_auto_20200803_0123'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='flow',
            field=django.contrib.postgres.fields.jsonb.JSONField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='flow_graph',
            field=models.TextField(default='test'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='num_semester',
            field=models.SmallIntegerField(default=1),
            preserve_default=False,
        ),
    ]
