# Generated by Django 3.0.8 on 2020-08-06 13:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0018_auto_20200806_1319'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='easiest_subject',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='hardest_subject',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
