# Generated by Django 3.0.8 on 2020-08-23 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0016_auto_20200804_1659'),
        ('course', '0019_auto_20200806_1327'),
    ]

    operations = [
    ]
