# Generated by Django 3.0.8 on 2020-08-23 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0022_auto_20200823_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='coordinator_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
