# Generated by Django 3.0.8 on 2020-12-28 09:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_adding_unaccent_query'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
