# Generated by Django 3.0.8 on 2020-12-31 05:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0031_adding_unaccent_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='corequisites',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='CoRequisite',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('corequisite', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subject_co', to='course.Subject')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='corequisite', to='course.Subject')),
            ],
        ),
    ]
