# Generated by Django 3.0.8 on 2022-05-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0035_auto_20210102_0122'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='occupied',
            field=models.CharField(default='0', max_length=3),
        ),
        migrations.AddField(
            model_name='offer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
