# Generated by Django 3.0.8 on 2020-07-19 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0002_auto_20200719_0506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.BigIntegerField(primary_key=True, serialize=False),
        ),
    ]
