# Generated by Django 3.0.8 on 2020-07-20 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0004_auto_20200720_0051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='department_id',
            new_name='department',
        ),
        migrations.CreateModel(
            name='CourseSubject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.PositiveSmallIntegerField()),
                ('status', models.CharField(choices=[('OB', 'Obrigatória'), ('OP', 'Optativa'), ('OP', 'Módulo Livre')], max_length=2)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Subject')),
            ],
        ),
    ]
