# Generated by Django 3.0.8 on 2020-07-23 03:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0009_auto_20200722_0613'),
    ]

    operations = [
        migrations.CreateModel(
            name='SemesterGrade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('semester', models.CharField(max_length=6)),
                ('room', models.CharField(max_length=3)),
                ('ss', models.PositiveSmallIntegerField()),
                ('ms', models.PositiveSmallIntegerField()),
                ('mm', models.PositiveSmallIntegerField()),
                ('mi', models.PositiveSmallIntegerField()),
                ('ii', models.PositiveSmallIntegerField()),
                ('sr', models.PositiveSmallIntegerField()),
                ('tr', models.PositiveSmallIntegerField()),
                ('tj', models.PositiveSmallIntegerField()),
                ('cc', models.PositiveSmallIntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='semester_grade', to='course.Subject')),
            ],
        ),
    ]
