# Generated by Django 3.0.8 on 2020-07-29 21:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0012_subject_already_set_prerequisite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='already_set_prerequisite',
        ),
    ]
