# Generated by Django 3.0.8 on 2020-08-03 00:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0013_remove_subject_already_set_prerequisite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equivalence',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abrangencia', models.CharField(max_length=10)),
                ('destino', models.CharField(max_length=6)),
                ('disciplina', models.CharField(max_length=6)),
                ('direcao', models.CharField(max_length=14)),
            ],
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.CharField(max_length=6)),
                ('equivalence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='course.Equivalence')),
            ],
        ),
    ]
