# Generated by Django 3.0.8 on 2020-08-06 13:19

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0017_auto_20200806_0452'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='equivalences',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='grade_infos',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='subject',
            name='pass_percent',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='subject',
            name='prerequisites',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
    ]
