# Generated by Django 3.0.8 on 2020-08-23 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0020_merge_20200823_2239'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='academic_degree',
            field=models.CharField(default='safe', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='coordinator_name',
            field=models.CharField(default='opa', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='course',
            name='is_ead',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='course',
            name='shift',
            field=models.CharField(choices=[('N', 'Noturno'), ('D', 'Diurno')], default='N', max_length=2),
            preserve_default=False,
        ),
    ]
