# Generated by Django 3.0.8 on 2020-08-23 22:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0021_auto_20200823_2240'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='begin_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='course',
            name='issue_date',
        ),
    ]
