# Generated by Django 3.0.8 on 2020-12-15 21:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0026_course_department'),
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('semester', models.CharField(max_length=7)),
                ('schedule', models.CharField(max_length=100)),
                ('students_qtd', models.CharField(max_length=3)),
                ('place', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='course',
            name='curriculum',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='mandatory_workload',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='opt_workload',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='course',
            name='total_workload',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='department',
            name='initials',
            field=models.CharField(default='BC', max_length=4),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='subject',
            name='code',
            field=models.CharField(max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='subject',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subject', to='course.Department'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='name',
            field=models.CharField(max_length=80),
        ),
        migrations.CreateModel(
            name='OfferTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_teachers', to='course.Offer')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offer_teachers', to='course.Teacher')),
            ],
        ),
        migrations.AddField(
            model_name='offer',
            name='department',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='course.Department'),
        ),
        migrations.AddField(
            model_name='offer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='course.Subject'),
        ),
        migrations.CreateModel(
            name='CourseCurriculum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_curriculum', to='course.Course')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='course_curriculum', to='course.Subject')),
            ],
            options={
                'unique_together': {('course', 'subject')},
            },
        ),
    ]
