# Generated by Django 3.0.8 on 2020-12-24 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0028_subject_offer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='offer',
            name='department',
        ),
        migrations.AlterField(
            model_name='offer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='course.Subject', unique=True),
        ),
    ]
