# Generated by Django 3.0.8 on 2020-12-24 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0029_auto_20201224_1528'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='course.Subject'),
        ),
    ]
