# Generated by Django 3.0.8 on 2020-12-31 22:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course', '0032_auto_20201228_0924'),
        ('course', '0033_auto_20201231_0559'),
    ]

    operations = [
    ]
