name: CI
on:
  pull_request:
    branches:
      - develop
      - master
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@master
      - name: Install modules
        run: yarn
      - name: Run ESLint
        run: yarn lint

